# AutoReplantCrops - Konfigurationsdatei

# Link: https://minecraft-heads.com/custom-heads
# (Mit diesen link kannst du das Kopf design 채ndern)
#
# kurtze erkl채rung:
# gehe auf die webseite: https://minecraft-heads.com/custom-heads
# suche dir einen Kopf aus und klcke drauf
# dan scrollst du runter bis du For Developers findest
# dort kopierst du den Value und f체gst ihn bei headTexture rein ~

# Zeit in Sekunden bis der Crop wieder gepflanzt wird
replant-delay: 1.5

# Crop-Typen, die unterst체tzt werden
crops:
  - WHEAT
  - CARROTS
  - POTATOES
  - BEETROOTS
